"""Phase 1 CAD ingestion: full path over golden STL, and STEP degradation.

Drives quarantine gate -> parse_ocr 5C -> chunk (§B) -> validate -> index against real STL
files (ASCII + binary) generated by trimesh, asserting the ExtractedModel metrics, the
canonical mesh, the part-card chunk text, and provenance carrying the CAD extraction tier.
STEP without OCP installed is asserted to route to review, never crash.
"""
from __future__ import annotations

import tempfile
from datetime import datetime, timezone
from pathlib import Path

import pytest
import trimesh

from ikip_contracts import ProcessingVersions, Provenance
from ikip_ingestion.extract import ExtractionTier, default_registry
from ikip_ingestion.extract.registry import MAGIC_READ_BYTES
from ikip_ingestion.extract.types import CadCoordinate, PmiNote
from ikip_ingestion.stages import parse_ocr, quarantine
from ikip_ingestion.stages.chunk import chunk_model
from ikip_ingestion.stages.index import InMemoryChunkWriter, index_chunks
from ikip_ingestion.stages.parse_ocr import Route
from ikip_ingestion.stages.quarantine import Disposition
from ikip_ingestion.stages.validate import validate_chunks


@pytest.fixture(scope="module")
def stl_files() -> dict[str, Path]:
    d = Path(tempfile.mkdtemp(prefix="cad-golden-"))
    box = trimesh.creation.box(extents=(10.0, 20.0, 30.0))
    ascii_p = d / "bracket_ascii.stl"
    bin_p = d / "bracket_bin.stl"
    box.export(str(ascii_p), file_type="stl_ascii")
    box.export(str(bin_p), file_type="stl")
    return {"ascii": ascii_p, "binary": bin_p}


def _provenance_for(model_tier: str) -> Provenance:
    return Provenance(
        source_document_id="doc-1",
        source_revision="v1",
        source_checksum="sha256:abc",
        processing_versions=ProcessingVersions(
            parser="step_occt|stl_trimesh",
            chunker="cad-structural:0.1",
            embedding_model="none",
            extraction_tier=model_tier,
        ),
        created_at=datetime.now(timezone.utc),
    )


@pytest.mark.parametrize("kind", ["ascii", "binary"])
def test_stl_full_path(stl_files: dict[str, Path], kind: str) -> None:
    path = stl_files[kind]
    reg = default_registry()

    # 1. Quarantine magic-byte gate admits the file.
    head = path.read_bytes()[:MAGIC_READ_BYTES]
    decision = quarantine.gate(head, path.name, reg)
    assert decision.disposition is Disposition.ADMIT
    assert decision.handler_key == "STL"

    # 2. parse_ocr routes to 5C and extracts in the sandbox.
    routed = parse_ocr.route_and_extract(path, path.name, registry=reg)
    assert routed.route is Route.CAD
    assert routed.cad is not None and routed.cad.ok
    model = routed.cad.model

    # ExtractedModel metrics (a 10x20x30 box).
    assert model.tier is ExtractionTier.FULL_GEOMETRY
    assert model.geometry_available and model.canonical_mesh is not None
    assert model.metrics.face_count == 12
    assert model.metrics.vertex_count == 8
    assert model.metrics.is_watertight is True
    assert abs(model.metrics.volume - 6000.0) < 1.0
    assert model.canonical_mesh.vertices and model.canonical_mesh.faces

    # 3. Chunk: exactly one part card for a single-part STL, with metrics in the text.
    prov = _provenance_for(model.tier.value)
    chunks = chunk_model(model, document_id="doc-1", provenance=prov)
    part_cards = [c for c in chunks if c.kind == "part_card"]
    assert len(part_cards) == 1
    card = part_cards[0]
    assert "triangles=12" in card.text
    assert "bbox=10.0x20.0x30.0" in card.text
    assert card.source_coordinates["cad_entity_type"] == "part"

    # 4. Validate gate passes, then 5. index writes rows idempotently.
    outcome = validate_chunks(chunks)
    assert outcome.ok, outcome.rejected
    writer = InMemoryChunkWriter()
    written = index_chunks(outcome.valid, writer)
    assert written == len(chunks)
    # Idempotent re-index writes nothing new.
    assert index_chunks(outcome.valid, writer) == 0
    assert writer.by_kind("part_card")[0]["extraction_tier"] == "full_geometry"


def test_pmi_chunks_carry_cad_coordinates(stl_files: dict[str, Path]) -> None:
    # STL has no PMI, so synthesize a model with PMI to exercise the §B PMI path + coords.
    reg = default_registry()
    routed = parse_ocr.route_and_extract(stl_files["binary"], "bracket_bin.stl", registry=reg)
    model = routed.cad.model
    from dataclasses import replace

    model = replace(
        model,
        pmi=[
            PmiNote(
                text="Ø30 H7 tolerance on main bore",
                coordinate=CadCoordinate(entity_type="pmi", entity_id="0:1:4", label="bore-tol"),
            )
        ],
    )
    prov = _provenance_for(model.tier.value)
    chunks = chunk_model(model, document_id="doc-1", provenance=prov)
    pmi = [c for c in chunks if c.kind == "pmi"]
    assert len(pmi) == 1
    assert pmi[0].source_coordinates["cad_entity_type"] == "pmi"
    assert pmi[0].source_coordinates["cad_entity_id"] == "0:1:4"
    assert validate_chunks(chunks).ok


def test_step_without_ocp_routes_to_review() -> None:
    reg = default_registry()
    d = Path(tempfile.mkdtemp())
    step = d / "assembly.step"
    step.write_bytes(b"ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('demo'),'2;1');\nENDSEC;\n")

    decision = quarantine.gate(step.read_bytes()[:MAGIC_READ_BYTES], step.name, reg)
    assert decision.disposition is Disposition.ADMIT  # recognized as STEP
    assert decision.handler_key == "STEP"

    routed = parse_ocr.route_and_extract(step, step.name, registry=reg)
    assert routed.route is Route.CAD
    assert not routed.cad.ok
    # Route the sandbox failure: toolkit-unavailable -> review, not reject.
    routed_decision = quarantine.route_extraction(routed.cad)
    assert routed_decision.disposition is Disposition.REVIEW
    assert "unavailable" in routed_decision.reason or "conversion" in routed_decision.reason


def test_validate_rejects_geometric_chunk_without_coordinates() -> None:
    # A part_card missing CAD coordinates must be rejected by the gate.
    from ikip_ingestion.stages.chunk import Chunk

    prov = _provenance_for("full_geometry")
    bad = Chunk(
        chunk_id="doc-1:part_card:0",
        document_id="doc-1",
        kind="part_card",
        text="Part: mystery",
        source_coordinates={},  # missing cad_entity_type
        provenance=prov,
    )
    outcome = validate_chunks([bad])
    assert not outcome.ok
    assert "source_coordinates" in outcome.rejected[0][1]
